
/*
 * 
 */

package com.ruanko.webserviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.ruanko.webservice.BcBankWebService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Dec 08 15:39:03 CST 2015
 * Generated source version: 2.3.0
 * 
 */


@WebServiceClient(name = "bcBankWebServiceImpl", 
                  wsdlLocation = "http://127.0.0.1/bcWebservice?wsdl",
                  targetNamespace = "http://webserviceImpl.ruanko.com/") 
public class BcBankWebServiceImpl extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://webserviceImpl.ruanko.com/", "bcBankWebServiceImpl");
    public final static QName BcBankWebServiceImplPort = new QName("http://webserviceImpl.ruanko.com/", "BcBankWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1/bcWebservice?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://127.0.0.1/bcWebservice?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public BcBankWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BcBankWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BcBankWebServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BcBankWebServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public BcBankWebServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BcBankWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BcBankWebService
     */
    @WebEndpoint(name = "BcBankWebServiceImplPort")
    public BcBankWebService getBcBankWebServiceImplPort() {
        return super.getPort(BcBankWebServiceImplPort, BcBankWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BcBankWebService
     */
    @WebEndpoint(name = "BcBankWebServiceImplPort")
    public BcBankWebService getBcBankWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BcBankWebServiceImplPort, BcBankWebService.class, features);
    }

}
