
package com.ruanko.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Dec 08 15:39:03 CST 2015
 * Generated source version: 2.3.0
 * 
 */

@WebFault(name = "AppException", targetNamespace = "http://webservice.ruanko.com/")
public class AppException_Exception extends Exception {
    public static final long serialVersionUID = 20151208153903L;
    
    private com.ruanko.webservice.AppException appException;

    public AppException_Exception() {
        super();
    }
    
    public AppException_Exception(String message) {
        super(message);
    }
    
    public AppException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AppException_Exception(String message, com.ruanko.webservice.AppException appException) {
        super(message);
        this.appException = appException;
    }

    public AppException_Exception(String message, com.ruanko.webservice.AppException appException, Throwable cause) {
        super(message, cause);
        this.appException = appException;
    }

    public com.ruanko.webservice.AppException getFaultInfo() {
        return this.appException;
    }
}
