
package com.ruanko.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.ruanko.webserviceimpl.BcBankWebServiceImpl;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.0
 * Tue Dec 08 15:39:03 CST 2015
 * Generated source version: 2.3.0
 * 
 */

public final class BcBankWebService_BcBankWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webserviceImpl.ruanko.com/", "bcBankWebServiceImpl");

    private BcBankWebService_BcBankWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = BcBankWebServiceImpl.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BcBankWebServiceImpl ss = new BcBankWebServiceImpl(wsdlURL, SERVICE_NAME);
        BcBankWebService port = ss.getBcBankWebServiceImplPort();  
        
        {
        System.out.println("Invoking pay...");
        java.lang.String _pay_arg0 = "";
        java.lang.String _pay_arg1 = "";
        java.lang.String _pay_arg2 = "";
        java.lang.String _pay_arg3 = "";
        float _pay_arg4 = 0.0f;
        try {
            int _pay__return = port.pay(_pay_arg0, _pay_arg1, _pay_arg2, _pay_arg3, _pay_arg4);
            System.out.println("pay.result=" + _pay__return);

        } catch (AppException_Exception e) { 
            System.out.println("Expected exception: AppException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
